# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07b1fe49e6a37667ca3fb7560e7077689d82b299b6e6dba729d452f04a6c71f5052ecd153aa563018035c218d7efdafdfee6238736a77015d7879e9f1001aaf4

test:
  secret_key_base: 02744a80b680c6680e6d7ae5b56d431daef0c74a2ec3e3223f3c4b883ec1f1a09deae5bcf16bfa55d2ac4717d4927d0594d9963bcba18bac514bf5c7848fb02e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
